name: Release

# on:
#   push:
#     branches:
#       - main
on: [push]

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@main
      - name: Get Release Notes
        env:
          COMMIT_TEXT: '${{ github.event.head_commit.message }}'
        run: |
          echo $COMMIT_TEXT
      - name: Set Version
        id: set-version
        run: echo "::set-output name=tag_version::$(sh ./.github/scripts/get-version.sh)"
      - name: Say Version
        run: |
          echo v${{ steps.set-version.outputs.tag_version }}
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.set-version.outputs.tag_version }}
          release_name: Release v${{ steps.set-version.outputs.tag_version }}
          body: |
            Release Changes:
              ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
